# Lectura de datos de matrices, 

In [1]:
# Procesar Datos de Tablas/Matrices
# Que son las librerias y para que se usan
# Seleccionar valores específicos de una matriz
# Leer archivos netcdf
# Realizar operaciones matemáticas/estadísticas en matrices/tablas

In [2]:
import numpy as np # numerical python
import netCDF4 as nc

#  Numpy arrays

In [3]:
# Ver presentación

In [4]:
spy = np.array([1, 4, 5.0, 6])

In [5]:
type(spy) # variable es un numpy arrray pero no dice que hay dentro de spy

numpy.ndarray

In [6]:
# Podemos utilizar el punto spy.dtype ya que dtype es una función de numpy

In [7]:
print(spy.dtype) # Tipo de datos dentro del array spy

float64


In [8]:
print(spy.shape) # tamaño de variable spy
print(np.shape(spy))
print(spy[3])
print(spy[-1])

(4,)
(4,)
6.0
6.0


In [9]:
print('primer valor en los datos:', spy[0]) # 0 es el indice 1 en Python


primer valor en los datos: 1.0


# Slicing data

Podemos seleccionar un indíce o una sección del vector

In [10]:
print(spy)

[1. 4. 5. 6.]


In [11]:
print(spy[2:]) # empieza en el índice 2 hasta el final
print(spy[1:3]) # empieza en el índice 1 pero no incluye el 3

[5. 6.]
[4. 5.]


In [12]:
# No tenemos que incluir el límite inferior ni superior
print(spy[:2]) # significa desde el índice 0 hasta el 4

[1. 4.]


In [13]:
print(np.mean(spy)) # numpy tiene funciones que realizan operaciones en el vector

4.0


In [14]:
print(spy.mean())
print(spy.std())

4.0
1.8708286933869707


# Reading netCDF

In [15]:
# Ahora utilizemos datos atmósfericos para algo más complicado

In [16]:
fileobj = nc.Dataset('ERA5_Coarse.nc') # Lee el archivo netcdf nc la extension

In [17]:
# netCDF network Common Data Form formato que guarda datos MULTIDIMENSIONALES

In [18]:
print(fileobj)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    history: Wed Nov 30 09:40:40 2022: ncks -F -d time,1,,10 ERA5_Coarse.nc ERA5_test.nc
    NCO: netCDF Operators version 4.7.6 (Homepage = http://nco.sf.net, Code = http://github.com/nco/nco)
    dimensions(sizes): latitude(180), longitude(360), time(76)
    variables(dimensions): float32 latitude(latitude), float32 longitude(longitude), int16 sp(time, latitude, longitude), int16 sst(time, latitude, longitude), int16 t2m(time, latitude, longitude), float32 t2m_F(time, latitude, longitude), int32 time(time), int16 tp(time, latitude, longitude), int16 u10(time, latitude, longitude), int16 v10(time, latitude, longitude)
    groups: 


In [19]:
print(fileobj.variables.keys())

dict_keys(['latitude', 'longitude', 'sp', 'sst', 't2m', 't2m_F', 'time', 'tp', 'u10', 'v10'])


In [20]:
print(fileobj.variables.keys()) # siempre revisar que variables hay en el archivo

dict_keys(['latitude', 'longitude', 'sp', 'sst', 't2m', 't2m_F', 'time', 'tp', 'u10', 'v10'])


In [21]:
# Guarda en la memoria virtual estas variables
lon = fileobj['longitude']
lat = fileobj['latitude']
time = fileobj['time']

In [22]:
print(lon)

<class 'netCDF4._netCDF4.Variable'>
float32 longitude(longitude)
    _FillValue: nan
    units: degrees_east
    long_name: longitude
unlimited dimensions: 
current shape = (360,)
filling on


In [23]:
print(lat) # nos da una explicación sobre la variable

<class 'netCDF4._netCDF4.Variable'>
float32 latitude(latitude)
    _FillValue: nan
    units: degrees_north
    long_name: latitude
unlimited dimensions: 
current shape = (180,)
filling on


In [24]:
sst = fileobj['sst'] 

In [25]:
print(sst) # cuantas dimensiones tiene esta variable

<class 'netCDF4._netCDF4.Variable'>
int16 sst(time, latitude, longitude)
    _FillValue: -32767
    units: K
    long_name: Sea surface temperature
    add_offset: 289.4649014722902
    scale_factor: 0.0006169772945977599
    missing_value: -32767
unlimited dimensions: 
current shape = (76, 180, 360)
filling on


In [26]:
sst = fileobj['sst'][:] # que son los dos puntitos

In [27]:
print(np.shape(sst))

(76, 180, 360)


In [28]:
print(sst.shape) # cuantas dimensiones tiene esta variable

(76, 180, 360)


Numpy tiene funciones útiles para analizar datos!

In [29]:
print(sst.std())
print(np.std(sst))

11.664515743159109
11.664515743159109


In [30]:
print(sst.mean()) # Si quieres el promedio de todos los datos

286.64469091892795


In [31]:
sst_C = sst - 273.15

In [32]:
print(sst_C.mean())

13.49469091892794


In [33]:
maxval, minval, stdval = np.max(sst_C), np.min(sst_C), np.std(sst_C)


In [34]:
print('Max SST:', maxval)
print('Min SST:', minval)
print('Desviación Standard:', stdval)

Max SST: 35.20181041451684
Min SST: -3.7202022151828373
Desviación Standard: 11.664515743159109


Como saber que funciones tiene numpy. Escribir np y después tab. Intentálo!

Cuando analizamos datos oceanográficos generalmente queremos saber el promedio sobre un area o tiempo específico

In [35]:
# Ir a la presentación

In [36]:
print(np.mean(sst_C, axis=0))

[[-1.6900627816757934 -1.6900627816757934 -1.6900627816757934 ...
  -1.6900627816757934 -1.6900627816757934 -1.6900627816757934]
 [-1.6900627816757934 -1.6900627816757934 -1.6900627816757934 ...
  -1.6900627816757934 -1.6900627816757934 -1.6900627816757934]
 [-1.6900627816757934 -1.6900627816757934 -1.6900627816757934 ...
  -1.6900627816757934 -1.6900627816757934 -1.6900627816757934]
 ...
 [-- -- -- ... -- -- --]
 [-- -- -- ... -- -- --]
 [-- -- -- ... -- -- --]]


In [37]:
# El promedio de la temperatura en cada lat y lon de todo el tiempo
print(np.mean(sst_C, axis=0).shape)  # axis =0 es sobre dimensión 0 (tiempo)

(180, 360)


In [38]:
# El promedio de la temperatura sobre todos los renglones (latitud)
print(np.mean(sst_C, axis=1).shape) # axis = 1 es sobre dimensión renglones (rows latitud)

(76, 360)


In [39]:
np.mean(sst_C, axis=0).mean(axis=1)

masked_array(data=[-1.6900627816757932, -1.690061857111865,
                   -1.6900600079840085, -1.6900535360365103,
                   -1.6900456208672703, -1.6891054521038797,
                   -1.686248324062011, -1.6792765192429853,
                   -1.6403246054695797, -1.5609386702966876,
                   -1.4461518023553004, -1.3082913781553274,
                   -1.1403758384320217, -0.943423783545596,
                   -0.6915690992465369, -0.4712881403343141,
                   -0.22907012259792267, 0.11508012411188989,
                   0.44889696132124224, 0.8914475881563392,
                   1.0429599563741545, 1.1663233833720656,
                   1.636103118506971, 2.241147593066227,
                   2.799852726299241, 3.269760396945605,
                   4.004396526135544, 4.060160309547734,
                   4.419624615004082, 4.77808907630022, 5.127337842051136,
                   5.597598327018603, 5.9094834041951305,
                   6.194083983

y que es axis=2?

In [40]:
a = np.array([[1, 2], [3, 4]], float) # crear una matriz de dos dimensiones tipo float
b = np.array([[5, 6], [7,8]], float)

print('Matrix A')
print(a)
print('Matrix B')
print(b)

Matrix A
[[1. 2.]
 [3. 4.]]
Matrix B
[[5. 6.]
 [7. 8.]]


In [41]:
np.concatenate((a,b)) # unir las dos matrices

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [42]:
np.concatenate((a,b), axis=1) # unir las dos matrices


array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])